<?php
$filter_object = array(
    'admin_module_pages' => array(
        'ua' => array(
            'id'           => 'Ідентифікатор',
            'active'       => 'Активність',
            'module'       => 'Модуль',
            'detail_page'  => 'Детальні сторінки',
            'dinamic_page' => 'Динамічні сторінки',
            'list_length'  => 'Використання мови',
            'meta_title'   => 'Title сторінки',
        ),
        'ru' => array(
            'id'           => 'Идентификатор',
            'active'       => 'Активность',
            'module'       => 'Модуль',
            'detail_page'  => 'Подробные страницы',
            'dinamic_page' => 'Динамические страницы',
            'list_length'  => 'Использование языка',
            'meta_title'   => 'Title страницы',
        ),
        'en' => array(
            'id'           => 'id',
            'active'       => 'Activity',
            'module'       => 'Module',
            'detail_page'  => 'Detail pages',
            'dinamic_page' => 'Dynamic_pages',
            'list_length'  => 'Language usage',
            'meta_title'   => 'Meta title',
        ),
    ),
    'admin_users_list'   => array(
        'ua' => array(
            'access'    => 'Доступ',
            'active'    => 'Активність',
            'name'      => 'Ім\'я',
            'last_name' => 'Прізвище',
            'login'     => 'Логін',
            'email'     => 'Email',
            'floor'     => 'Стать',
            'country'   => 'Країна',
            'city'      => 'Місто',
        ),
        'ru' => array(
            'access'    => 'Доступ',
            'active'    => 'Активность',
            'name'      => 'Имя',
            'last_name' => 'Фамилия',
            'login'     => 'Логин',
            'email'     => 'Email',
            'floor'     => 'Пол',
            'country'   => 'Страна',
            'city'      => 'Город',
        ),
        'en' => array(
            'access'    => 'Access',
            'active'    => 'Activity',
            'name'      => 'Name',
            'last_name' => 'Last name',
            'login'     => 'Login',
            'email'     => 'Email',
            'floor'     => 'Sex',
            'country'   => 'Country',
            'city'      => 'City',
        ),
    ),
    'admin_type_mails'   => array(
        'ua' => array(
            'active'      => 'Активність',
            'theme_list'  => 'Тема листа',
            'name'        => 'Назва',
            'symbol_code' => 'Символьний код',
            'hidden_copy' => 'Прихована копія',
            'text'        => 'Текст',
        ),
        'ru' => array(
            'active'      => 'Активность',
            'theme_list'  => 'Тема письма',
            'name'        => 'Название',
            'symbol_code' => 'Символьный код',
            'hidden_copy' => 'Скрытая копия',
            'text'        => 'Текст',
        ),
        'en' => array(
            'active'      => 'Activity',
            'theme_list'  => 'Letter theme',
            'name'        => 'Title',
            'symbol_code' => 'Symbol code',
            'hidden_copy' => 'Hidden copy',
            'text'        => 'Text',
        ),
    ),
    'products'           => array(
        'ua' => array(
            'active'         => 'Активність',
            'name_ua'        => 'Назва UA',
            'name_ru'        => 'Назва RU',
            'symbol_code'    => 'Символьний код',
            'availability'   => 'Наявність',
            'price'          => 'Ціна',
            'garanty'        => 'Гарантія',
            'form_ua'        => 'Форма UA',
            'text_ua'        => 'Текст UA',
            'description_ua' => 'Опис матрацу UA',
            'anatoming'      => 'Анатомія',
            'ortopeding'     => 'Ортопедія',

        ),
        'ru' => array(
            'active'         => 'Активность',
            'name_ua'        => 'Название UA',
            'name_ru'        => 'Название RU',
            'symbol_code'    => 'Cимвольный код',
            'availability'   => 'Наличие',
            'price'          => 'Цена',
            'garanty'        => 'Гарантия',
            'form_ua'        => 'Форма UA',
            'text_ua'        => 'Текст UA',
            'description_ua' => 'Описание матраса UA',
            'anatoming'      => 'Анатомия',
            'ortopeding'     => 'Ортопедия',
        ),
        'en' => array(
            'active'         => 'Activity',
            'name_ua'        => 'Name UA',
            'name_ru'        => 'Name RU',
            'symbol_code'    => 'Symbol code',
            'availability'   => 'Availability',
            'price'          => 'Price',
            'garanty'        => 'Garanty',
            'form_ua'        => 'Form UA',
            'text_ua'        => 'Text UA',
            'description_ua' => 'Description UA',
            'anatoming'      => 'Anatomy',
            'ortopeding'     => 'Orthopedy',
        ),
    ),
);