<?php
$filter_object = array(
    'admin_module_pages' => array(
        'ua' => array(
            'id'           => 'Ідентифікатор',
            'active'       => 'Активність',
            'module'       => 'Модуль',
            'detail_page'  => 'Детальні сторінки',
            'dinamic_page' => 'Динамічні сторінки',
            'list_length'  => 'Використання мови',
            'meta_title'   => 'Title сторінки',
        ),
        'ru' => array(
            'id'           => '',
            'active'       => '',
            'module'       => '',
            'detail_page'  => '',
            'dinamic_page' => '',
            'list_length'  => '',
            'meta_title'   => '',
        ),
        'en' => array(
            'id'           => '',
            'active'       => '',
            'module'       => '',
            'detail_page'  => '',
            'dinamic_page' => '',
            'list_length'  => '',
            'meta_title'   => '',
        ),
    ),
    'admin_users_list'   => array(
        'ua' => array(
            'access'    => 'Доступ',
            'active'    => 'Активність',
            'name'      => 'Ім\'я',
            'last_name' => 'Фамілія',
            'login'     => 'Логін',
            'email'     => 'Email',
            'floor'     => 'Стать',
            'country'   => 'Країна',
            'city'      => 'Місто',
        ),
        'ru' => array(
            'access'    => '',
            'active'    => '',
            'name'      => '',
            'last_name' => '',
            'login'     => '',
            'email'     => '',
            'floor'     => '',
            'country'   => '',
            'city'      => '',
        ),
        'en' => array(
            'access'    => '',
            'active'    => '',
            'name'      => '',
            'last_name' => '',
            'login'     => '',
            'email'     => '',
            'floor'     => '',
            'country'   => '',
            'city'      => '',
        ),
    ),
    'admin_type_mails'   => array(
        'ua' => array(
            'active'      => 'Активність',
            'theme_list'  => 'Тема листа',
            'name'        => 'Назва',
            'symbol_code' => 'Символьний код',
            'hidden_copy' => 'Скрита копія',
            'text'        => 'Текст',
        ),
        'ru' => array(
            'active'      => '',
            'theme_list'  => '',
            'name'        => '',
            'symbol_code' => '',
            'hidden_copy' => '',
            'text'        => '',
        ),
        'en' => array(
            'active'      => '',
            'theme_list'  => '',
            'name'        => '',
            'symbol_code' => '',
            'hidden_copy' => '',
            'text'        => '',
        ),
    ),
    'products'           => array(
        'ua' => array(
            'active'         => 'Активність',
            'name_ua'        => 'Назва UA',
            'name_ru'        => 'Назва RU',
            'symbol_code'    => 'Символьний код',
            'availability'   => 'Наявність',
            'price'          => 'Ціна',
            'garanty'        => 'Гарантія',
            'form_ua'        => 'Форма',
            'text_ua'        => 'Текст',
            'description_ua' => 'Опис матрацу',
            'anatoming'      => 'Анатомія',
            'ortopeding'     => 'Ортопедія',

        ),
        'ru' => array(
            'active'         => '',
            'name_ua'        => '',
            'name_ru'        => '',
            'symbol_code'    => '',
            'availability'   => '',
            'price'          => '',
            'garanty'        => '',
            'form_ua'        => '',
            'text_ua'        => '',
            'description_ua' => '',

            'anatoming'      => '',
            'ortopeding'     => '',
            ),
        'en' => array(
            'active'         => '',
            'name_ua'        => '',
            'name_ru'        => '',
            'symbol_code'    => '',
            'availability'   => '',
            'price'          => '',
            'garanty'        => '',
            'form_ua'        => '',
            'text_ua'        => '',
            'description_ua' => '',
            'anatoming'      => '',
            'ortopeding'     => '',
            ),
    ),
);